### ISSUE TITLE
Implement Animations features (easy to use)

### ISSUE THREAD

**Issue by loicmaes** [MultiMC-Suite/MultiMC-API#36]
**Is your feature request related to a problem? Please describe.**
NO PROBLEM HERE!!!! JUST WANT TO ANIMATE SOMETHING.

**Describe the solution you'd like**
I just wanna animate some stuff on my server (without performances issues) and I think It could be cool to setup an animation Object with some built-in templates and let me animate my stuff easily.

**Describe alternatives you've considered**
JUST DO THE JOB BROO!!!

**Additional context**
Look down!
👌 

---

👊

**Comment by Xen0Xys** [comment]
Good idea, may be done one day.
